# Generated by Django 3.2.8 on 2021-10-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=21)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('state', models.CharField(max_length=2)),
                ('data_r', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
