# Generated by Django 3.2.8 on 2022-01-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=2056)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=21)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('state', models.CharField(max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('child', models.BooleanField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('buy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('USD', 'Доллар'), ('EUR', 'Евро')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('statuscode', models.PositiveSmallIntegerField()),
                ('path', models.CharField(max_length=256)),
                ('responsetime', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
    ]
