# Generated by Django 3.2.8 on 2021-10-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rate_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='car',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='child',
        ),
    ]
