# Generated by Django 3.2.8 on 2021-10-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20211016_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='child',
            field=models.BooleanField(default=True, max_length=5),
            preserve_default=False,
        ),
    ]
