# Generated by Django 3.2.8 on 2021-10-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_rate_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='data_r',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='salary',
        ),
    ]
