# Generated by Django 3.2.8 on 2021-10-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20211028_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
