# Generated by Django 3.2.8 on 2021-10-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_rate_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
