# Generated by Django 3.2.8 on 2021-11-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_alter_rate_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=2056)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
