# Generated by Django 3.2.8 on 2021-12-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_rate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('buy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=3)),
            ],
        ),
    ]
