# Generated by Django 3.2.8 on 2021-12-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_rate2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('statuscode', models.PositiveSmallIntegerField()),
                ('path', models.CharField(max_length=256)),
                ('responsetime', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
