# Generated by Django 3.2.8 on 2021-12-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0012_responselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate2',
            name='type',
            field=models.CharField(choices=[('USD', 'Доллар'), ('EUR', 'Евро')], max_length=3),
        ),
    ]
